In [1]:
import pandas as pd

In [49]:
cluster_path = '/Users/linda/Downloads/samples_cluster_stats2.parquet'
df = pd.read_parquet(cluster_path)
df = df.reset_index()

In [50]:
df[df['cluster_label'] == 415].head()

,cluster_label,D_perc,protein_confidence,count,mean_seq_len,min_seq_len,median_seq_len,max_seq_len,std_seq_len,seq_len_arr,embedding,model,bitscore_mean,bitscore_std_dev,evalue_mean,evalue_std_dev,ratio_pairs_wo_blast
416,415,0.136959,77.044306,7,31144.0,1450,40485.0,53197,19026.35339,"[18085, 16633, 44770, 1450, 53197, 40485, 43388]",SeqVec,HDBSCAN,89.83017,258.90204,0.674981,1.791583,0.000958

In [11]:
cluster_path = '/Users/linda/Downloads/model_outputs_B2-HDBSCAN-SeqVec-all_protein_combos_per_cluster.parquet'
df = pd.read_parquet(cluster_path)
df.head()

  query_protein target_protein  cluster
1        O96009         P00797        0
2        O96009         P07339        0
3        O96009         P0DJD7        0
4        O96009         P0DJD8        0
5        O96009         P0DJD9        0

In [14]:
cluster_path = '/Users/linda/Downloads/samples_proteins_w_blast.parquet'
df = pd.read_parquet(cluster_path)
df.head()

  query_protein target_protein  cluster  bitscore         evalue
0        O96009         P00797        0     312.0  2.770000e-103
1        O96009         P07339        0     390.0  1.150000e-133
2        O96009         P0DJD7        0     290.0   3.770000e-95
3        O96009         P0DJD8        0     291.0   2.610000e-95
4        O96009         P0DJD9        0     292.0   9.250000e-96

In [21]:
cluster_path = '/Users/linda/Downloads/samples_proteins_with_clusters_n_3d_embed.parquet'
protein_df = pd.read_parquet(cluster_path)
protein_df.head()

      protein  cluster_label         x          y         z
0  A0A024R1R8             -1 -5.638844   1.582528 -5.042023
1  A0A024RBG1             83 -1.777370   2.982981 -0.836539
2  A0A024RCN7             -1  1.113939   2.127296  1.512760
3  A0A075B6H5             -1  1.022581   9.176342  5.943778
4  A0A075B6H7            105  0.701044  12.698147  8.236269

In [16]:
cluster_path = '/Users/linda/Downloads/samples_all_protein_combos_per_cluster.parquet'
df = pd.read_parquet(cluster_path)
df.head()

  query_protein target_protein  cluster
1        O96009         P00797        0
2        O96009         P07339        0
3        O96009         P0DJD7        0
4        O96009         P0DJD8        0
5        O96009         P0DJD9        0

In [20]:
cluster_path = '/Users/linda/Downloads/structure_files_sequences_sequences.parquet'
confidence_df = pd.read_parquet(cluster_path)
confidence_df.head()

,pdbx_db_accession,db_code,db_name,protein_id,pdbx_seq_one_letter_code,protein_filename,confidence_pLDDT
0,A0A024R1R8,A0A024R1R8_HUMAN,UNP,A0A024R1R8,MSSHEGGKKKALKQPKKQAKEMDEEEKAFKQKQKEEQKKLEVLKAK...,AF-A0A024R1R8-F1-model_v1,73.21
1,A0A024RBG1,NUD4B_HUMAN,UNP,A0A024RBG1,MMKFKPNQTRTYDREGFKKRAACLCFRSEQEDEVLLVSSSRYPDQW...,AF-A0A024RBG1-F1-model_v1,85.18
2,A0A024RCN7,A0A024RCN7_HUMAN,UNP,A0A024RCN7,MERSFVWLSCLDSDSCNLTFRLGEVESHACSPSLLWNLLTQYLPPG...,AF-A0A024RCN7-F1-model_v1,54.38
3,A0A075B6H5,A0A075B6H5_HUMAN,UNP,A0A075B6H5,METVVTTLPREGGVGPSRKMLLLLLLLGPGSGLSAVVSQHPSRVIC...,AF-A0A075B6H5-F1-model_v1,86.88
4,A0A075B6H7,KV37_HUMAN,UNP,A0A075B6H7,MEAPAQLLFLLLLWLPDTTREIVMTQSPPTLSLSPGERVTLSCRAS...,AF-A0A075B6H7-F1-model_v1,90.02

In [80]:
left = protein_df.set_index('protein')
right = confidence_df.set_index('pdbx_db_accession')
new = left.join(right)
new = new.reset_index()

In [81]:
new

,protein,cluster_label,x,y,z,db_code,db_name,protein_id,pdbx_seq_one_letter_code,protein_filename,confidence_pLDDT
0,A0A024R1R8,-1,-5.638844,1.582528,-5.042023,A0A024R1R8_HUMAN,UNP,A0A024R1R8,MSSHEGGKKKALKQPKKQAKEMDEEEKAFKQKQKEEQKKLEVLKAK...,AF-A0A024R1R8-F1-model_v1,73.21
1,A0A024RBG1,83,-1.777370,2.982981,-0.836539,NUD4B_HUMAN,UNP,A0A024RBG1,MMKFKPNQTRTYDREGFKKRAACLCFRSEQEDEVLLVSSSRYPDQW...,AF-A0A024RBG1-F1-model_v1,85.18
2,A0A024RCN7,-1,1.113939,2.127296,1.512760,A0A024RCN7_HUMAN,UNP,A0A024RCN7,MERSFVWLSCLDSDSCNLTFRLGEVESHACSPSLLWNLLTQYLPPG...,AF-A0A024RCN7-F1-model_v1,54.38
3,A0A075B6H5,-1,1.022581,9.176342,5.943778,A0A075B6H5_HUMAN,UNP,A0A075B6H5,METVVTTLPREGGVGPSRKMLLLLLLLGPGSGLSAVVSQHPSRVIC...,AF-A0A075B6H5-F1-model_v1,86.88
4,A0A075B6H7,105,0.701044,12.698147,8.236269,KV37_HUMAN,UNP,A0A075B6H7,MEAPAQLLFLLLLWLPDTTREIVMTQSPPTLSLSPGERVTLSCRAS...,AF-A0A075B6H7-F1-model_v1,90.02
...,...,...,...,...,...,...,...,...,...,...,...
20499,U3KPV4,-1,2.422364,1.313682,1.058688,A3LT2_HUMAN,UNP,U3KPV4,MALKEGLRAWKRIFWRQILLTLGLLGLFLYGLPKFRHLEALIPMGV...,AF-U3KPV4-F1-model_v1,90.60
20500,V9GZ13,-1,2.518447,2.083623,-1.167358,V9GZ13_HUMAN,UNP,V9GZ13,MKNTSWIRKNWLLVAGISFIGVHLGTYFLQRSAKQSVKFQSQSKQK...,AF-V9GZ13-F1-model_v1,78.64
20501,W5XKT8,-1,1.312074,0.064005,0.231258,SACA6_HUMAN,UNP,W5XKT8,MALLALASAVPSALLALAVFRVPAWACLLCFTTYSERLRICQMFVG...,AF-W5XKT8-F1-model_v1,86.75
20502,W6CW81,-1,-0.996502,1.827311,0.674279,PYDC5_HUMAN,UNP,W6CW81,MESKYKEILLLTSLDNITDEELDRFKCFLPDEFNIATGKLHTLNST...,AF-W6CW81-F1-model_v1,52.00
20503,X6R8D5,-1,-0.261166,0.270918,1.365292,GUCNB_HUMAN,UNP,X6R8D5,MGRKEHESPSQPHMCGWEDSQKPSVPSHGPKTPSCKGVKAPHSSRP...,AF-X6R8D5-F1-model_v1,58.60

In [82]:
new['length'] = new['pdbx_seq_one_letter_code'].map(lambda p: len(p)) 
new = new.drop(['db_code', 'db_name', 'protein_id', 'pdbx_seq_one_letter_code', 'protein_filename'], axis=1)

In [83]:
new = new.rename(columns={'x': 'X', 'y': 'Y', 'z': 'Z', 'confidence_pLDDT': 'confidence', 'cluster_label': 'Cluster Label'})

In [84]:
confidence_path = '/Users/linda/Downloads/all_proteins_with_confidence.parquet'
new.to_parquet(confidence_path)

In [52]:
cluster_path = '/Users/linda/Downloads/annotations_pairwise_evaluation_metrics.parquet'
df = pd.read_parquet(cluster_path)
df.head()

,query_protein,query_protein_length,target_protein,target_protein_length,aligned_length,rmsd,tmalign_score
0,AF-Q8N1S5-F1-model_v1,342,AF-P48449-F1-model_v1,732,190,7.43,0.30487
1,AF-Q8N1S5-F1-model_v1,342,AF-Q8N6C7-F1-model_v1,128,70,5.22,0.14206
2,AF-Q8N1S5-F1-model_v1,342,AF-Q9NW08-F1-model_v1,1133,156,6.86,0.26120
3,AF-Q8N1S5-F1-model_v1,342,AF-C9J3I9-F1-model_v1,102,48,3.15,0.12211
4,AF-Q8N1S5-F1-model_v1,342,AF-Q02930-F1-model_v1,508,123,6.88,0.20843

In [54]:
def rename_proteins(row):
    row.query_protein = row.query_protein.split('-')[1]
    row.target_protein = row.target_protein.split('-')[1]
    return row
renamed_df = df.apply(rename_proteins, axis='columns')

In [73]:
new

          protein  Cluster Label         X          Y         Z  confidence
0      A0A024R1R8             -1 -5.638844   1.582528 -5.042023       73.21
1      A0A024RBG1             83 -1.777370   2.982981 -0.836539       85.18
2      A0A024RCN7             -1  1.113939   2.127296  1.512760       54.38
3      A0A075B6H5             -1  1.022581   9.176342  5.943778       86.88
4      A0A075B6H7            105  0.701044  12.698147  8.236269       90.02
...           ...            ...       ...        ...       ...         ...
20499      U3KPV4             -1  2.422364   1.313682  1.058688       90.60
20500      V9GZ13             -1  2.518447   2.083623 -1.167358       78.64
20501      W5XKT8             -1  1.312074   0.064005  0.231258       86.75
20502      W6CW81             -1 -0.996502   1.827311  0.674279       52.00
20503      X6R8D5             -1 -0.261166   0.270918  1.365292       58.60

[20504 rows x 6 columns]

In [55]:
renamed_df

,query_protein,query_protein_length,target_protein,target_protein_length,aligned_length,rmsd,tmalign_score
0,Q8N1S5,342,P48449,732,190,7.43,0.30487
1,Q8N1S5,342,Q8N6C7,128,70,5.22,0.14206
2,Q8N1S5,342,Q9NW08,1133,156,6.86,0.26120
3,Q8N1S5,342,C9J3I9,102,48,3.15,0.12211
4,Q8N1S5,342,Q02930,508,123,6.88,0.20843
...,...,...,...,...,...,...,...
20,Q15005,226,Q7Z3S7,1137,138,6.76,0.30687
21,P57729,211,P0C5J1,330,137,5.15,0.41416
22,Q96A33,483,Q99959,881,219,7.37,0.27522
23,Q12798,172,Q96NJ5,620,101,5.43,0.32949
24,P07550,413,Q6SJ96,375,126,7.04,0.18249

In [59]:
table_path = '/Users/linda/Downloads/pairwise_proteins.parquet'
renamed_df.to_parquet(table_path)

In [57]:
renamed_df

,query_protein,query_protein_length,target_protein,target_protein_length,aligned_length,rmsd,tmalign_score
0,Q8N1S5,342,P48449,732,190,7.43,0.30487
1,Q8N1S5,342,Q8N6C7,128,70,5.22,0.14206
2,Q8N1S5,342,Q9NW08,1133,156,6.86,0.26120
3,Q8N1S5,342,C9J3I9,102,48,3.15,0.12211
4,Q8N1S5,342,Q02930,508,123,6.88,0.20843
...,...,...,...,...,...,...,...
20,Q15005,226,Q7Z3S7,1137,138,6.76,0.30687
21,P57729,211,P0C5J1,330,137,5.15,0.41416
22,Q96A33,483,Q99959,881,219,7.37,0.27522
23,Q12798,172,Q96NJ5,620,101,5.43,0.32949
24,P07550,413,Q6SJ96,375,126,7.04,0.18249

In [62]:
renamed_df[renamed_df['query_protein'] == new['protein'][0]]

Empty DataFrame
Columns: [query_protein, query_protein_length, target_protein, target_protein_length, aligned_length, rmsd, tmalign_score]
Index: []

In [63]:
new['protein'][0]

'A0A024R1R8'

In [72]:
len(confidence_df[confidence_df['pdbx_db_accession'] == 'Q8N1S5']['pdbx_seq_one_letter_code'].iloc(0)[0])

342

In [79]:
new

,protein,Cluster Label,X,Y,Z,confidence,length
0,A0A024R1R8,-1,-5.638844,1.582528,-5.042023,73.21,64
1,A0A024RBG1,83,-1.777370,2.982981,-0.836539,85.18,181
2,A0A024RCN7,-1,1.113939,2.127296,1.512760,54.38,75
3,A0A075B6H5,-1,1.022581,9.176342,5.943778,86.88,130
4,A0A075B6H7,105,0.701044,12.698147,8.236269,90.02,116
...,...,...,...,...,...,...,...
20499,U3KPV4,-1,2.422364,1.313682,1.058688,90.60,340
20500,V9GZ13,-1,2.518447,2.083623,-1.167358,78.64,50
20501,W5XKT8,-1,1.312074,0.064005,0.231258,86.75,324
20502,W6CW81,-1,-0.996502,1.827311,0.674279,52.00,113
20503,X6R8D5,-1,-0.261166,0.270918,1.365292,58.60,127